### ISSUE TITLE
expanded_hypernym sometimes ends up in a circular reference.

### ISSUE THREAD

**Issue by stefanberndtsson** [doches/rwordnet#2]
Synsets for some words end up in a non-ending loop (which causes ruby to abort when the stack gets exhausted).

This piece of code seems to reproduce the problem for me:

<pre>
require 'wordnet'
l = WordNet::WordNetDB.find("blink")[1]
puts l.synsets[1].expanded_hypernym
</pre>

Other words triggering the error somewhere in the result lists (may not be in array offsets 1 and 1 as the provided example): "bound", "check", "draw", "limit"

**Comment by doches** [comment]
I realise this is an ancient bug, but what the hell. It looks like this is caused by a loop in WordNet's hypernym relationship (which is logically invalid but *still exists in the data of course*).
