### ISSUE TITLE
require 'rwordnet'

### ISSUE THREAD

**Issue by mihao** [doches/rwordnet#25]
This is a great gem, but it cannot coexist with the `wordnet` gem, as both are required with `require 'wordnet'`. I had both gems installed and it took me some time before I realised that I didn't require the gem I wanted. Wouldn't `require 'rwordnet'` be a better choice here?

**Comment by doches** [comment]
_Sigh_. 

I _definitely_ agree with you; the gem is called `rwordnet`, and it's always bugged me a little that you use it with `require 'wordnet'`. Changing the name (!) is a pretty breaking change, but I guess that's what semantic versioning is for, eh?

**Comment by doches** [comment]
Aaand version-bumped to `2.0.0`, which changes `require 'wordnet'` to `require 'rwordnet'`. Thanks for kicking me to make this change!
