### ISSUE TITLE
break gloss into definition and examples?

### ISSUE THREAD

**Issue by academyofzhuang** [doches/rwordnet#26]
word.gloss  returns a string.  It contains word definition and optionally some example sentences.    

It would be more convenient for the user to break it into "definition" and examples.

A peek into other project source code shows it could be done with regex.   

````js
// https://github.com/NaturalNode/natural/blob/master/lib/natural/wordnet/data_file.js#L53
// break "gloss" into definition vs. examples
var glossArray = data[1].split("; ");
var definition = glossArray[0];
var examples = glossArray.slice(1); 
````

**Comment by doches** [comment]
I'd rather not do this in the library, since it's trivial for users of the library to do:

```ruby
# Fetch glosses from wordnet
glosses = WordNet::Lemma.find("fruit", :noun).synsets.map { |synset| synset.gloss }
# Split returned glosses into [definition, example1, example2, ...]
split_glosses = glosses.map { |gloss| gloss.split("; ") }
```

It would also be a _massively_ breaking change for existing users, as any existing consumer of `#gloss` is expecting a string rather than an array. Thanks for the suggestion, though!
