### ISSUE TITLE
How do I get related words

### ISSUE THREAD

**Issue by abhisheksarka** [doches/rwordnet#30]
Is there a way to find related words for a given word?

**Comment by doches** [comment]
Sort of -- I'm afraid that WordNet operates on a somewhat different level than just "related words". You have to go from a given word into its synsets, find related synsets (you'll have to specify the relation you're interested in), and then extract words from the related synsets. For example: first find the lemma for your word, specifying its part of speech:

```ruby
require 'rwordnet'

verb = WordNet::Lemma.find("make", :verb)
```

Then find related synsets (in this case, antonyms):

```ruby
antonyms =  verb.synsets.map { |synset| synset.antonyms }.flatten
```

Finally, extract the words for related synsets:

```ruby
related_words = antonyms.map { |antonym| antonym.words }.flatten
p related_words
# => ["unmake", "undo", "break"]
```

https://github.com/doches/rwordnet/blob/master/lib/rwordnet/synset.rb has some shorthand methods for fetching specific relations (e.g. `#antonyms`), but you can also use the general-purpose `#relation` (https://github.com/doches/rwordnet/blob/master/lib/rwordnet/synset.rb#L186) in conjunction with any of the WordNet-defined relations (the crazy symbols from https://github.com/doches/rwordnet/blob/master/lib/rwordnet/pointers.rb). So, for example:

```ruby
# Find other verbs in the same "verb group":
p WordNet::Lemma.find("make", :verb).synsets.map { |synset| synset.relation("$") }.flatten.map { |synset| synset.words }.flatten.uniq
# => ["make", "create", "produce", "net", "sack", "sack_up", "clear", "do", "build", "gain", "take_in", "earn", "realize", "realise", "pull_in", "bring_in", "have", "get", "work", "reach", "attain", "hit", "arrive_at", "cook", "fix", "ready", "prepare", "make_up", "seduce", "feign", "sham", "pretend", "affect", "dissemble", "draw"] 
```
