### ISSUE TITLE
Does search for location work?

### ISSUE THREAD

**Issue by yenism5217** [doches/rwordnet#6]
When I look for a location word such as "Baltimore" in the database within this gem, it returned with a nil result.  However, on the WordNet 3.0 database that I downloaded from the WordNet website, I can get a full result of any location words.  

1.  Are words such as location words missing from the gem's database?  It seems that the answer is yes.

2.  Then I dug into the dict/index.noun and dict/data.noun files in the gem, I could not find any location words by comparing the same files in the WordNet database dict directory.  Is it possible that this is the reason that I was not able to find a location word in the gem?  Also, it failed to find location words after I set WordNetDB.path to my local WordNet database.

Thank you!

**Comment by doches** [comment]
I'm closing this issue as I can't repro it (also, it's *ancient*).

```ruby
WordNet::Lemma.find('baltimore', :noun).to_s
# "baltimore,n" 
WordNet::Lemma.find('detroit', :noun).to_s
# "detroit,n"
```
